<?php

define('SHANTI_JSLDA_PATH', drupal_get_path('module','shanti_jslda'));

function shanti_jslda_menu() {
	return array(
    'shanti_jslda/default/%/%/%' => array(
    	'title' => t('Default jsLDA Page'),
      'page callback' => 'shanti_jslda_default',
			'page arguments' => array(2,3,4),
      'type' => MENU_CALLBACK,
      'access arguments' => array('access content'),
    ),	
	);
}

function shanti_jslda_default($corpus_file_id, $stopwords_file_id, $topicn = 25) {
	$corpus = file_load($corpus_file_id);
	$stopws = file_load($stopwords_file_id);
	$corpus_url = file_create_url($corpus->uri);
	$stopws_url = file_create_url($stopws->uri);
	return theme('shanti_jslda_default_page', array('corpus_url' => $corpus_url, 'stopwords_url' => $stopws_url, 'topicn' => $topicn));
}

function shanti_jslda_theme($existing, $type, $theme, $path) {
	return array(
		'shanti_jslda_default_page' => array(
			'variables' => array('corpus_url' => '', 'stopwords_url' => '', 'topicn' => 25),
			'template' => 'shanti-jslda-default-page',
			'path' => SHANTI_JSLDA_PATH,
		),
	);
}

function shanti_jslda_views_api() {
  return array(
    'api' => 3,
    'path' =>  SHANTI_JSLDA_PATH . '/views',
  );
}